---
# tasks file for Ubuntu2004-CIS
- name: Check OS version and family
  fail:
      msg: "This role can only be run agaist Ubuntu 20.04. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  when:
      - not ansible_distribution == "Ubuntu"
      - not ansible_distribution_release == "focal"
  tags:
      - always

- name: Check ansible version
  fail:
      msg: You must use ansible 2.3 or greater!
  when: not ansible_version.full is version_compare('2.3', '>=')
  tags:
      - always

- include_role: prelim.yml
  become: true
  tags:
      - prelim_tasks
      - always

- include_role: section1.yml
  become: true
  when: ubuntu2004cis_section1
  tags: section1

- include_role: section2.yml
  become: true
  when: ubuntu2004cis_section2
  tags: section2

- include_role: section3.yml
  become: true
  when: ubuntu2004cis_section3
  tags: section3

- include_role: section4.yml
  become: true
  when: ubuntu2004cis_section4
  tags: section4

- include_role: section5.yml
  become: true
  when: ubuntu2004cis_section5
  tags: section5

- include_role: section6.yml
  become: true
  when: ubuntu2004cis_section6
  tags: section6

- include_role: post.yml
  become: true
  tags:
      - post_tasks
      - always
