name: Molecule

on:
  push:
    branches:
    - main
    - dev*
  pull_request:

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Molecule
        uses: gofrolist/molecule-action@master
        with:
          molecule_command: test
          molecule_args: -d docker
          #molecule_working_dir: thedatabaseme/cookbooks/ansible/molecule/molecule_test_role
        env:
          ANSIBLE_FORCE_COLOR: '1'
  release:
    needs:
      - molecule
    runs-on: ubuntu-latest
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
          branch: main
